
language: node_js
node_js: stable

os:
    - linux

env:
    # dependencies for Atom
    global:
        - APM_TEST_PACKAGES="agda-mode language-agda"
        - ATOM_LINT_WITH_BUNDLED_NODE="true"

    matrix:
        - AGDA_VERSION=2.5.1
        - AGDA_VERSION=2.4.2.5

script:
    - docker pull banacorn/agda:$AGDA_VERSION
    - chmod u+x build-package.sh
    - ./build-package.sh

services:
    - docker

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - spec

git:
  depth: 10

sudo: false

addons:
    apt:
        packages:
            # for Atom
            - build-essential
            - git
            - libgnome-keyring-dev
            - fakeroot
